# Generated by Django 4.0.3 on 2022-06-12 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('f_name', models.TextField()),
                ('l_name', models.TextField()),
                ('password', models.TextField()),
            ],
        ),
    ]
